import 'user_data.dart';

class AppStrings {
  // ข้อมูลคำแปล (Dictionary)
  static const Map<String, Map<String, String>> _data = {
    'th': {
      'menu_home': 'หน้าแรก',
      'menu_leaderboard': 'อันดับ',
      'menu_lesson': 'บทเรียน',
      'menu_vocab': 'คลังศัพท์',
      'menu_blog': 'บล็อก',
      'menu_more': 'เมนู',
      'menu_profile': 'โปรไฟล์',
      'profile': 'โปรไฟล์',
      'statistics': 'สถิติ',
      'menu_ai_tutor': 'AI ติวเตอร์',
      'daily_quest': 'ภารกิจประจำวัน',
      'practice_mode': 'โหมดฝึกฝน',
      'continue_learning': 'เรียนต่อ',
      'stats': 'สถิติ',
      'settings': 'ตั้งค่า',
      'dark_mode': 'โหมดมืด',
      'language': 'ภาษา',
      'reset': 'รีเซ็ตข้อมูล',
      'history_title': 'ประวัติการเรียน',
      'history_empty': 'ยังไม่มีประวัติการเรียน',
      'edit_name': 'แก้ไขชื่อ',
      'sign_out': 'ออกจากระบบ',
      'app_language': 'ภาษาแอป',
      'learning_language': 'ภาษาที่เรียน',
      'change_app_language': 'เปลี่ยนภาษาของเมนูและข้อความในแอป',
      'change_learning_language': 'เลือกภาษาที่คุณต้องการเรียนในแอป',
      'current_language': 'ภาษาปัจจุบัน',
      'select_language': 'เลือกภาษา',
      'reset_all_data': 'รีเซ็ตข้อมูลทั้งหมด',
      'friends': 'เพื่อน',
      'friends_count': 'เพื่อน',
      'view_all': 'ดูทั้งหมด',
      'no_friends': 'ยังไม่มีเพื่อน',
      'add_friends': 'เพิ่มเพื่อนเพื่อเริ่มสนทนา!',
      'friends_groups': 'เพื่อน & กลุ่ม',
      'community': 'ชุมชน',
      'leaderboard_title': 'อันดับผู้เล่น',
      'rank': 'อันดับที่',
      'level': 'ระดับ',
      'you': 'คุณ',
      'no_data': 'ยังไม่มีข้อมูล',
      'collect_xp_quest': 'เก็บ XP ให้ครบ 50 แต้ม',
      'add_vocab_quest': 'เพิ่มคำศัพท์ใหม่ 5 คำ',
      'completed': 'เสร็จสิ้น',
      'course': 'คอร์สเรียน',
      'add_vocabulary': 'เพิ่มคำศัพท์',
      'no_vocabulary': 'ยังไม่ได้เพิ่มคำศัพท์',
      'add_new_vocabulary': 'เพิ่มคำศัพท์ใหม่',
      'app_language_changed_th': 'เปลี่ยนภาษาแอปเป็นภาษาไทยแล้ว',
      'app_language_changed_en': 'Changed app language to English',
      'learning_language_changed': 'เปลี่ยนภาษาที่เรียนเป็น',
      'learning_map': 'แผนที่การเรียนรู้',
      'vocabulary_word': 'คำศัพท์',
      'reading': 'คำอ่าน',
      'meaning': 'คำแปล',
      'category': 'หมวดหมู่',
      'save': 'บันทึก',
      'friend_requests': 'คำขอ',
      'add_friend': 'เพิ่มเพื่อน',
      'test_api_create_lesson': 'ทดสอบ API & สร้างบทเรียน',
      'thai_language': 'ภาษาไทย',
      'english_language': 'English',
      'lessons': 'บทเรียน',
      'my_vocabulary': 'ของฉัน',
      'ai_tutor_welcome': 'สวัสดีครับ! 👋 \nวันนี้อยากฝึกแต่งประโยค{langName} หรือให้ผมช่วยแปลคำไหนบอกได้เลยนะครับ!',
      'ai_tutor_fix_sentence': '✨ ช่วยแก้ประโยค',
      'ai_tutor_translate': 'แปลเป็น{langName}',
      'ai_tutor_practice_pronunciation': '🗣️ ฝึกออกเสียง',
      'please_fill_word_and_meaning': 'กรุณากรอกคำศัพท์และคำแปล',
      'save_success': 'บันทึกสำเร็จ!',
      'create_group_to_start': 'สร้างกลุ่มใหม่เพื่อเริ่มชุมชน!',
      'delete_friend': 'ลบเพื่อน',
      'block_friend': 'บล็อกเพื่อน',
      'friend_request_sent': 'ส่งคำขอเพื่อนแล้ว',
      'friend_request_exists': 'มีคำขออยู่แล้ว',
      'accept_friend_request': 'ยอมรับคำขอเพื่อนแล้ว',
      'no_friend_requests': 'ไม่มีคำขอเพื่อนใหม่',
      'wants_to_be_friend': 'ต้องการเป็นเพื่อนกับคุณ',
      'edit_your_name': 'แก้ไขชื่อของคุณ',
      'new_name': 'ชื่อใหม่',
      'cancel': 'ยกเลิก',
      'delete_vocabulary': 'ลบคำศัพท์?',
      'delete_vocabulary_confirm': 'คุณต้องการลบคำว่า "{word}" ใช่ไหม?',
      'no_vocab_in_lesson': 'ยังไม่มีคำศัพท์ในบทนี้',
      'practice_pronunciation': 'ฝึกออกเสียง',
      'block': 'บล็อก',
      'accept': 'ยอมรับ',
      'reject': 'ปฏิเสธ',
      'are_you_sure': 'คุณแน่ใจหรือไม่?',
      'delete': 'ลบ',
      'confirm_reset': 'ยืนยันการรีเซ็ต',
      'reset_warning': 'ข้อมูลการเรียน XP และคำศัพท์ที่เพิ่มเองจะหายไปทั้งหมด\nคุณแน่ใจหรือไม่?',
      'reset_success': 'รีเซ็ตข้อมูลเรียบร้อย',
      'confirm': 'ยืนยัน',
      'name_changed_success': 'เปลี่ยนชื่อเรียบร้อยแล้ว',
      'please_enter_name': 'กรุณากรอกชื่อของคุณ',
      'connect_google_account': 'เชื่อมต่อ Google Account เพื่อบันทึกข้อมูลของคุณ',
      'sign_out_confirm': 'คุณต้องการออกจากระบบใช่ไหม?\nข้อมูลการเรียนจะยังคงอยู่',
      'connected_account': 'บัญชีที่เชื่อมต่อ',
      'account_not_connected': 'ยังไม่ได้เชื่อมต่อบัญชี',
      'sign_in_with_google': 'เข้าสู่ระบบด้วย Google',
      'app_data': 'ข้อมูลในแอป',
      'blog_allies': 'บล็อก & แนวร่วม',
      'no_posts_yet': 'ยังไม่มีโพสต์',
      'start_posting_to_find_allies': 'เริ่มต้นโพสต์หาแนวร่วมกันเลย!',
      'recommend_friend': 'แนะนำเพื่อน',
      'start_learning_to_see_history': 'เริ่มเรียนเพื่อดูประวัติการเรียนของคุณ',
      'signing_in': 'กำลังเข้าสู่ระบบ...',
      'no_email': 'ไม่มีอีเมล',
      'search_by_name_or_email': 'ค้นหาด้วยชื่อหรืออีเมล',
      'search_results': 'ผลการค้นหา',
      'add': 'เพิ่ม',
      'sign_in_with_google_to_save': 'เข้าสู่ระบบด้วย Google เพื่อบันทึกความคืบหน้าของคุณ',
      'error_occurred': 'เกิดข้อผิดพลาด',
      'select_avatar': 'เลือก Avatar',
      'avatar_changed_success': 'เปลี่ยน Avatar เรียบร้อยแล้ว',
      'close': 'ปิด',
      'sign_in': 'เข้าสู่ระบบ',
      'skip_for_now': 'ข้ามไปก่อน (ลองใช้ฟรี)',
      'completed_at': 'เสร็จสิ้นเมื่อ',
      'call': 'โทรหา',
      'call_button': 'โทร',
      'start': 'เริ่ม',
      'with': 'กับ',
      'create_post': 'สร้างโพสต์',
      'share': 'แชร์',
      'unit_greetings': 'การทักทาย',
      'unit_introduce': 'แนะนำตัวเอง',
      'unit_numbers_time': 'ตัวเลข & เวลา',
      'unit_food_drinks': 'อาหาร & เครื่องดื่ม',
      'unit_travel': 'การเดินทาง',
      'lesson_locked_message': 'ต้องเรียนบทก่อนหน้าให้จบก่อนนะ!',
      'lesson_clear_previous': 'เคลียร์ด่านก่อนหน้าให้จบก่อนนะ!',
      'lesson_basic_greetings': 'พื้นฐานการทักทาย',
      'lesson_introduce_self': 'แนะนำตัวเอง',
      'lesson_numbers_prices': 'ตัวเลขและราคา',
      'lesson_restaurant': 'ร้านอาหาร',
      'lesson_travel': 'การเดินทาง',
      'answer_incorrect': 'คำตอบไม่ถูกต้อง',
      'see_explanation': 'มาดูคำอธิบายกัน',
      'correct_answer': 'คำตอบที่ถูกต้อง:',
      'explanation': 'คำอธิบาย:',
      'understood_continue': 'เข้าใจแล้ว ไปต่อเลย',
      'check_answer': 'ตรวจคำตอบ',
      'continue_next': 'ไปต่อเลย',
      'answer_correct': 'คำตอบถูกต้อง!',
      'example': 'เช่น',
      'lesson_completed': 'บทเรียนสำเร็จ!',
      'lesson_completed_message': 'สุดยอดมาก! 🎉\nคุณได้รับ +50 XP \nและปลดล็อคบทเรียนถัดไปแล้ว',
      'acknowledged': 'รับทราบ',
      'setup_api_keys': 'ตั้งค่า API Keys',
      'please_setup_api_keys': 'กรุณาตั้งค่า API Keys เพื่อใช้งาน AI Tutor และ Voice features',
      'understood': 'เข้าใจแล้ว',
      'speech_to_text_unavailable': 'Speech-to-Text ไม่พร้อมใช้งาน',
      'voice_service_not_configured': 'Voice service ไม่ได้ตั้งค่า กรุณาตรวจสอบ API Key',
      'error_playing_audio': 'เกิดข้อผิดพลาดในการเล่นเสียง',
      'need_microphone_permission': 'ต้องการ permission ในการใช้ microphone',
      'error_recording': 'เกิดข้อผิดพลาดในการบันทึกเสียง',
      'error_stopping_listen': 'เกิดข้อผิดพลาดในการหยุดฟัง',
      'typing': 'กำลังพิมพ์...',
      'online': 'Online',
      'listening': 'กำลังฟัง... พูดได้เลย',
      'ai_typing': 'AI กำลังพิมพ์...',
      'type_message': 'พิมพ์ข้อความ...',
      'sign_in_success': 'เข้าสู่ระบบสำเร็จ!',
      'sign_out_success': 'ออกจากระบบเรียบร้อยแล้ว',
      'years_ago': 'ปีที่แล้ว',
      'months_ago': 'เดือนที่แล้ว',
      'days_ago': 'วันที่แล้ว',
      'hours_ago': 'ชั่วโมงที่แล้ว',
      'minutes_ago': 'นาทีที่แล้ว',
      'just_now': 'เมื่อสักครู่',
      'chat_room': 'ห้องสนทนา',
      'group': 'กลุ่ม',
      'mine': 'ของฉัน',
      'no_rooms_yet': 'ยังไม่มีห้อง',
      'create_room_to_start': 'สร้างห้องใหม่เพื่อเริ่มสนทนา!',
      'no_groups_yet': 'ยังไม่มีกลุ่ม',
      'create_group_to_start_community': 'สร้างกลุ่มใหม่เพื่อเริ่มชุมชน!',
      'not_joined_any_room_or_group': 'คุณยังไม่ได้เข้าร่วมห้องหรือกลุ่ม',
      'joined_groups': 'กลุ่มที่เข้าร่วม',
      'create_new_room': 'สร้างห้องใหม่',
      'create_room': 'สร้างห้อง',
      'create_group': 'สร้างกลุ่ม',
      'joined_rooms': 'ห้องที่เข้าร่วม',
      'select_room_type': 'เลือกประเภทห้องที่ต้องการสร้าง',
      'post': 'โพสต์',
      'post_success': 'โพสต์สำเร็จ!',
      'title': 'หัวข้อ',
      'write_interesting_title': 'เขียนหัวข้อที่น่าสนใจ...',
      'please_enter_title': 'กรุณาใส่หัวข้อ',
      'content': 'เนื้อหา',
      'write_your_content': 'เขียนเนื้อหาของคุณ...',
      'please_enter_content': 'กรุณาใส่เนื้อหา',
      'image_url_optional': 'URL รูปภาพ (ไม่บังคับ)',
      'tags': 'แท็ก',
      'add_tag': 'เพิ่มแท็ก...',
      'learn_for_level': 'เรียนรู้{topic} สำหรับระดับ {level}',
      'topic_basic_greetings': 'คำทักทายพื้นฐาน',
      'topic_numbers_quantity': 'ตัวเลขและจำนวน',
      'topic_colors_vocab': 'สีและคำศัพท์พื้นฐาน',
      'topic_family_people': 'ครอบครัวและคน',
      'topic_food_drinks': 'อาหารและเครื่องดื่ม',
      'topic_days_time': 'วันและเวลา',
      'topic_basic_verbs': 'คำกริยาพื้นฐาน',
      'topic_basic_adjectives': 'คำคุณศัพท์พื้นฐาน',
      'topic_greetings': 'คำทักทาย',
      'topic_numbers': 'ตัวเลข',
      'topic_colors': 'สี',
      'topic_family': 'ครอบครัว',
      'topic_complex_sentences': 'ประโยคที่ซับซ้อนขึ้น',
      'topic_te_form': 'คำกริยารูป te-form',
      'topic_ta_form': 'คำกริยารูป ta-form',
      'topic_particles': 'คำช่วย (Particles)',
      'topic_desires': 'การแสดงความต้องการ',
      'topic_comparison': 'การเปรียบเทียบ',
      'topic_intermediate_vocab': 'คำศัพท์ระดับกลาง',
      'topic_intermediate_grammar': 'ไวยากรณ์ระดับกลาง',
      'topic_short_articles': 'การอ่านบทความสั้น',
      'topic_email_writing': 'การเขียนอีเมล',
    },
    'en': {
      'menu_home': 'Home',
      'menu_leaderboard': 'Leaderboard',
      'menu_lesson': 'Lessons',
      'menu_vocab': 'Vocabulary',
      'menu_blog': 'Blog',
      'menu_more': 'More',
      'menu_profile': 'Profile',
      'profile': 'Profile',
      'statistics': 'Statistics',
      'menu_ai_tutor': 'AI Tutor',
      'daily_quest': 'Daily Quests',
      'practice_mode': 'Practice Mode',
      'continue_learning': 'CONTINUE',
      'stats': 'Stats',
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'reset': 'Reset Data',
      'history_title': 'History',
      'history_empty': 'No learning history yet',
      'edit_name': 'Edit Name',
      'sign_out': 'Sign Out',
      'app_language': 'App Language',
      'learning_language': 'Learning Language',
      'change_app_language': 'Change the language of menus and text in the app',
      'change_learning_language': 'Select the language you want to learn in the app',
      'current_language': 'Current Language',
      'select_language': 'Select Language',
      'reset_all_data': 'Reset All Data',
      'friends': 'Friends',
      'friends_count': 'Friends',
      'view_all': 'View All',
      'no_friends': 'No friends yet',
      'add_friends': 'Add friends to start chatting!',
      'friends_groups': 'Friends & Groups',
      'community': 'Community',
      'leaderboard_title': 'Leaderboard',
      'rank': 'Rank',
      'level': 'Level',
      'you': 'You',
      'no_data': 'No data yet',
      'collect_xp_quest': 'Collect 50 XP points',
      'add_vocab_quest': 'Add 5 new words',
      'completed': 'Completed',
      'course': 'Courses',
      'add_vocabulary': 'Add Vocabulary',
      'no_vocabulary': 'No vocabulary added yet',
      'add_new_vocabulary': 'Add New Vocabulary',
      'app_language_changed_th': 'Changed app language to Thai',
      'app_language_changed_en': 'Changed app language to English',
      'learning_language_changed': 'Changed learning language to',
      'learning_map': 'Learning Map',
      'vocabulary_word': 'Vocabulary',
      'reading': 'Reading',
      'meaning': 'Meaning',
      'category': 'Category',
      'save': 'Save',
      'friend_requests': 'Requests',
      'add_friend': 'Add Friend',
      'test_api_create_lesson': 'Test API & Create Lesson',
      'thai_language': 'Thai',
      'english_language': 'English',
      'lessons': 'Lessons',
      'my_vocabulary': 'My Own',
      'ai_tutor_welcome': 'Hello! 👋 \nToday, would you like to practice making sentences in {langName}, or do you need help translating any words?',
      'ai_tutor_fix_sentence': '✨ Fix Sentence',
      'ai_tutor_translate': 'Translate to {langName}',
      'ai_tutor_practice_pronunciation': '🗣️ Practice Pronunciation',
      'please_fill_word_and_meaning': 'Please fill in vocabulary and meaning',
      'save_success': 'Saved successfully!',
      'create_group_to_start': 'Create a new group to start a community!',
      'delete_friend': 'Delete Friend',
      'block_friend': 'Block Friend',
      'friend_request_sent': 'Friend request sent',
      'friend_request_exists': 'Request already exists',
      'accept_friend_request': 'Friend request accepted',
      'no_friend_requests': 'No new friend requests',
      'wants_to_be_friend': 'wants to be your friend',
      'edit_your_name': 'Edit Your Name',
      'new_name': 'New Name',
      'cancel': 'Cancel',
      'delete_vocabulary': 'Delete Vocabulary?',
      'delete_vocabulary_confirm': 'Do you want to delete the word "{word}"?',
      'no_vocab_in_lesson': 'No vocabulary in this lesson yet',
      'practice_pronunciation': 'Practice Pronunciation',
      'block': 'Block',
      'accept': 'Accept',
      'reject': 'Reject',
      'are_you_sure': 'Are you sure?',
      'delete': 'Delete',
      'confirm_reset': 'Confirm Reset',
      'reset_warning': 'All learning data, XP, and custom vocabulary will be deleted.\nAre you sure?',
      'reset_success': 'Data reset successfully',
      'confirm': 'Confirm',
      'name_changed_success': 'Name changed successfully',
      'please_enter_name': 'Please enter your name',
      'connect_google_account': 'Connect Google Account to save your data',
      'sign_out_confirm': 'Do you want to sign out?\nYour learning data will be saved',
      'connected_account': 'Connected Account',
      'account_not_connected': 'Account not connected',
      'sign_in_with_google': 'Sign in with Google',
      'app_data': 'App Data',
      'blog_allies': 'Blog & Allies',
      'no_posts_yet': 'No posts yet',
      'start_posting_to_find_allies': 'Start posting to find allies!',
      'recommend_friend': 'Recommend Friend',
      'start_learning_to_see_history': 'Start learning to see your history',
      'signing_in': 'Signing in...',
      'no_email': 'No email',
      'search_by_name_or_email': 'Search by name or email',
      'search_results': 'Search Results',
      'add': 'Add',
      'sign_in_with_google_to_save': 'Sign in with Google to save your progress',
      'error_occurred': 'An error occurred',
      'select_avatar': 'Select Avatar',
      'avatar_changed_success': 'Avatar changed successfully',
      'close': 'Close',
      'sign_in': 'Sign In',
      'skip_for_now': 'Skip for now (Try free)',
      'completed_at': 'Completed at',
      'call': 'Call',
      'call_button': 'Call',
      'start': 'Start',
      'with': 'with',
      'create_post': 'Create Post',
      'share': 'Share',
      'unit_greetings': 'Greetings',
      'unit_introduce': 'Introduce Yourself',
      'unit_numbers_time': 'Numbers & Time',
      'unit_food_drinks': 'Food & Drinks',
      'unit_travel': 'Travel',
      'lesson_locked_message': 'You must complete the previous lessons first!',
      'lesson_clear_previous': 'Clear the previous level first!',
      'lesson_basic_greetings': 'Basic Greetings',
      'lesson_introduce_self': 'Introduce Yourself',
      'lesson_numbers_prices': 'Numbers and Prices',
      'lesson_restaurant': 'Restaurant',
      'lesson_travel': 'Travel',
      'answer_incorrect': 'Incorrect Answer',
      'see_explanation': 'Let\'s look at the explanation',
      'correct_answer': 'Correct Answer:',
      'explanation': 'Explanation:',
      'understood_continue': 'Understood, continue',
      'check_answer': 'Check Answer',
      'continue_next': 'Continue',
      'answer_correct': 'Correct Answer!',
      'example': 'e.g.',
      'lesson_completed': 'Lesson Completed!',
      'lesson_completed_message': 'Excellent! 🎉\nYou earned +50 XP \nand unlocked the next lesson',
      'acknowledged': 'Acknowledged',
      'setup_api_keys': 'Setup API Keys',
      'please_setup_api_keys': 'Please setup API Keys to use AI Tutor and Voice features',
      'understood': 'Understood',
      'speech_to_text_unavailable': 'Speech-to-Text is not available',
      'voice_service_not_configured': 'Voice service is not configured. Please check API Key',
      'error_playing_audio': 'Error playing audio',
      'need_microphone_permission': 'Microphone permission required',
      'error_recording': 'Error recording audio',
      'error_stopping_listen': 'Error stopping listening',
      'typing': 'Typing...',
      'online': 'Online',
      'listening': 'Listening... You can speak now',
      'ai_typing': 'AI is typing...',
      'type_message': 'Type message...',
      'sign_in_success': 'Sign in successful!',
      'sign_out_success': 'Sign out successful',
      'years_ago': 'years ago',
      'months_ago': 'months ago',
      'days_ago': 'days ago',
      'hours_ago': 'hours ago',
      'minutes_ago': 'minutes ago',
      'just_now': 'just now',
      'chat_room': 'Chat Room',
      'group': 'Group',
      'mine': 'Mine',
      'no_rooms_yet': 'No rooms yet',
      'create_room_to_start': 'Create a new room to start chatting!',
      'no_groups_yet': 'No groups yet',
      'create_group_to_start_community': 'Create a new group to start a community!',
      'not_joined_any_room_or_group': 'You haven\'t joined any room or group',
      'joined_groups': 'Joined Groups',
      'create_new_room': 'Create New Room',
      'create_room': 'Create Room',
      'create_group': 'Create Group',
      'joined_rooms': 'Joined Rooms',
      'select_room_type': 'Select the type of room you want to create',
      'post': 'Post',
      'post_success': 'Post created successfully!',
      'title': 'Title',
      'write_interesting_title': 'Write an interesting title...',
      'please_enter_title': 'Please enter a title',
      'content': 'Content',
      'write_your_content': 'Write your content...',
      'please_enter_content': 'Please enter content',
      'image_url_optional': 'Image URL (Optional)',
      'tags': 'Tags',
      'add_tag': 'Add tag...',
      'learn_for_level': 'Learn {topic} for {level} level',
      'topic_basic_greetings': 'Basic Greetings',
      'topic_numbers_quantity': 'Numbers and Quantity',
      'topic_colors_vocab': 'Colors and Basic Vocabulary',
      'topic_family_people': 'Family and People',
      'topic_food_drinks': 'Food and Drinks',
      'topic_days_time': 'Days and Time',
      'topic_basic_verbs': 'Basic Verbs',
      'topic_basic_adjectives': 'Basic Adjectives',
      'topic_greetings': 'Greetings',
      'topic_numbers': 'Numbers',
      'topic_colors': 'Colors',
      'topic_family': 'Family',
      'topic_complex_sentences': 'Complex Sentences',
      'topic_te_form': 'Te-form Verbs',
      'topic_ta_form': 'Ta-form Verbs',
      'topic_particles': 'Particles',
      'topic_desires': 'Expressing Desires',
      'topic_comparison': 'Comparison',
      'topic_intermediate_vocab': 'Intermediate Vocabulary',
      'topic_intermediate_grammar': 'Intermediate Grammar',
      'topic_short_articles': 'Reading Short Articles',
      'topic_email_writing': 'Email Writing',
    },
  };

  // ฟังก์ชันดึงคำแปล (ต้องเรียกใน Widget ที่มี ValueListenableBuilder ถึงจะเปลี่ยนสดๆ)
  static String t(String key, {Map<String, String>? params}) {
    String lang = UserData.appLanguage.value;
    // ถ้าไม่มีภาษานั้นให้ใช้ th เป็นหลัก
    String text = _data[lang]?[key] ?? _data['th']?[key] ?? key;
    
    // แทนที่ parameters ถ้ามี
    if (params != null) {
      params.forEach((key, value) {
        text = text.replaceAll('{$key}', value);
      });
    }
    
    return text;
  }
}